#!/usr/bin/env node
"use strict";

var co = require('co');
var colors = require('colors/safe');
var fs = require('fs');
var path = require('path');
var ProgressBar = require('progress');

var ffprobe = require('./ffprobe');
var stat = require('./stat');
var encoder = require('./encoder');
var subtitles = require('./subtitles');
var trash = require('./trash');

var script = path.basename(__filename);
var args = process.argv.slice(2);
var cwd = process.cwd();

if (args.length != 1) {
  console.error(`Usage: ${script} <input file>`);
  process.exit(1)
}

var filename = args[0];

co(function*() {
  yield stat(filename);

  console.log('getting metadata');
  let metadata = yield ffprobe(filename);

  console.log('looking for subs')
  let sub_file = yield subtitles.download(filename);
  if (sub_file) {
    console.log(`${colors.green('⇩')} ${path.relative(cwd, sub_file)}`)
  }
  console.log('moving to encode step..')


  let progress_bar = new ProgressBar(':filename :bar :percent :etas', {
    total: 10000,
    width: 40,
    incomplete: colors.bgWhite(' '),
    complete: colors.bgGreen(' ')
  });

  let new_file = yield encoder.encode_with_progress_bar(
    filename,
    metadata,
    sub_file,
    progress_bar
  );

  if (new_file) {
    let renames = yield trash([sub_file, filename]);
    for (let rename of renames) {
      console.log(`${rename.from} ${colors.green('⇨')} ${rename.to}`);
    }
  } else {
    console.log(`${path.relative(cwd, filename)} is already encoded correctly`)
  }
}).catch(function(error) {
  console.log(error);
})
